### ISSUE TITLE
Boot Loop on M5STACK FIRE

### ISSUE THREAD

**Issue by insurgus** [gitnabeshin/M5Stack_CWTrainer#4]
Having the following boot loop occur.

rst:0x3 (SW_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
ets Jul 29 2019 12:21:46

**Comment by gitnabeshin** [comment]
@insurgus 
@Montecri fixed this problem. Thank you very much.
